const THEME_STORAGE_KEY='cost-center-directory-theme';
const allowedThemes=['light','dark','blue','sand'];
const savedTheme=localStorage.getItem(THEME_STORAGE_KEY);
document.documentElement.dataset.theme=allowedThemes.includes(savedTheme)?savedTheme:'light';
const state={allData:[],currentFilter:'all',currentDepartment:'all',query:'',selectedId:null};
const $=id=>document.getElementById(id);
const el={summary:$('summary'),cards:$('cards'),count:$('record-count'),search:$('searchInput'),clear:$('clearSearch'),hint:$('search-hint'),dialog:$('detailDialog'),close:$('closeDetail'),title:$('detailTitle'),center:$('detailCostCenter'),booking:$('detailBooking'),contract:$('detailContract'),notes:$('detailNotes'),amount:$('detailAmount'),status:$('detailStatus'),share:$('shareBtn'),copyCenter:$('copyCenter'),copyCard:$('copyCard'),toast:$('toast'),departmentFilters:$('departmentFilters'),departmentCount:$('departmentCount'),detailDepartment:$('detailDepartment')};
const digitMap={'٠':'0','١':'1','٢':'2','٣':'3','٤':'4','٥':'5','٦':'6','٧':'7','٨':'8','٩':'9','۰':'0','۱':'1','۲':'2','۳':'3','۴':'4','۵':'5','۶':'6','۷':'7','۸':'8','۹':'9'};
const synonyms={
 'مضخه':['مضخات','pump','pumps'],'خزان':['خزانات','tank','tanks'],'مبادل':['مبادل حراري','exchanger','heat exchanger'],'رافعه':['ونش','crane'],'صيانه':['اصلاح','ترميم','maintenance','repair'],'تنظيف':['غسيل','cleaning'],'تبريد':['مياه التبريد','cooling','cooling water'],'خرسانه':['خرسانيه','قواعد خرسانية','concrete'],'اضاءه':['اناره','lighting'],'عدادات':['قياس','meters','metering'],'حمايه مهبطيه':['cathodic protection'],'صمام':['صمامات','valve','valves'],'ضاغط':['ضواغط','compressor','compressors'],'وقود':['fuel','fuel oil'],'مصفاه':['المصفاة','refinery'],'عماله':['قوى عاملة','manpower','labor'],'عامل حفاز':['catalyst']
};
function normalize(v=''){return String(v).replace(/[٠-٩۰-۹]/g,d=>digitMap[d]||d).toLowerCase().replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/ة/g,'ه').replace(/[\u064B-\u065F\u0670\u0640]/g,'').replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim()}
const compact=v=>normalize(v).replace(/\s/g,'');
const clean=v=>v==null?'':String(v).trim().replace(/^(["'])|(["'])$/g,'');
const money=v=>new Intl.NumberFormat('ar-LY',{style:'currency',currency:'LYD',maximumFractionDigits:0}).format(Number(v||0));
function expand(q){const n=normalize(q),set=new Set(n.split(' ').filter(Boolean));for(const [key,vals] of Object.entries(synonyms)){const group=[normalize(key),...vals.map(normalize)];if(group.some(x=>n.includes(x)||set.has(x)))group.forEach(x=>{set.add(x);x.split(' ').forEach(t=>set.add(t))})}return [...set]}
function score(record,q){if(!q)return {score:1,reason:''};const nq=normalize(q),cq=compact(q),cc=compact(record.cost_center),bn=compact(record.booking_number),details=normalize(record.contract_details),notes=normalize(record.notes),department=normalize(record.department);let s=0,reason='';if(cc===cq){s+=5000;reason='تطابق كامل مع مركز التكلفة'}else if(cc.includes(cq)){s+=1000;reason='تطابق مركز التكلفة'}if(bn===cq){s+=4700;reason=reason||'تطابق كامل مع رقم الحجز'}else if(bn.includes(cq)){s+=900;reason=reason||'تطابق رقم الحجز'}if(department.includes(nq)){s+=1400;reason=reason||'تطابق اسم القسم'}const tokens=expand(q);let matched=0;for(const t of tokens){const ct=compact(t);if(!ct)continue;if(details.includes(t)||compact(record.contract_details).includes(ct)){s+=160;matched++;reason=reason||'تطابق تفاصيل العمل'}else if(notes.includes(t)){s+=70;matched++;reason=reason||'تطابق الملاحظات'}}const digits=cq.replace(/\D/g,'');if(digits.length>=2&&compact(record.contract_details).includes(digits)){s+=220;reason=reason||'تطابق رمز المعدة'}if(matched&&matched>=Math.min(tokens.length,2))s+=300;return {score:s,reason}}
function records(){return state.allData.map(r=>({record:r,...score(r,state.query)})).filter(x=>(state.currentDepartment==='all'||x.record.department===state.currentDepartment)&&(!state.query||x.score>=70)&&(state.currentFilter==='all'||state.currentFilter==='review'&&x.record.needs_review||state.currentFilter==='clear'&&!x.record.needs_review)).sort((a,b)=>b.score-a.score||String(a.record.cost_center).localeCompare(String(b.record.cost_center)))}
function renderSummary(items){const data=items.map(x=>x.record),sum=data.reduce((a,r)=>a+Number(r.amount_lyd||0),0),departments=new Set(data.map(r=>r.department).filter(Boolean)).size;el.summary.innerHTML=`<article class="metric glass primary"><span>السجلات الظاهرة</span><strong>${data.length}</strong></article><article class="metric glass blue"><span>إجمالي القيمة</span><strong>${money(sum)}</strong></article><article class="metric glass warn"><span>الأقسام الظاهرة</span><strong>${departments}</strong></article>`}
function card(x){const r=x.record,status=r.needs_review?'تحتاج مراجعة':'مكتملة البيانات';return `<article class="record glass" data-id="${r.id}"><div class="department-line"><span class="department-badge">${clean(r.department)||'غير محدد'}</span></div><div class="record-top"><span class="booking">${clean(r.booking_number)||'—'}</span><span class="status ${r.needs_review?'review':'ok'}">${status}</span></div><h3 class="contract">${clean(r.contract_details)||'دون وصف'}</h3><div class="center-box"><span>مركز التكلفة</span><strong>${clean(r.cost_center)||'—'}</strong></div><div class="money">${money(r.amount_lyd)}</div>${clean(r.notes)?`<div class="notes">ملاحظات: ${clean(r.notes)}</div>`:''}${x.reason?`<div class="notes">✓ ${x.reason}</div>`:''}<div class="card-actions"><button class="view" data-action="view">عرض البطاقة</button><button class="share" data-action="share">مشاركة</button></div></article>`}
function renderDepartments(){const departments=[...new Set(state.allData.map(r=>clean(r.department)).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ar'));el.departmentCount.textContent=`${departments.length} أقسام`;el.departmentFilters.innerHTML=[`<button class="department-btn ${state.currentDepartment==='all'?'active':''}" data-department="all">جميع الأقسام</button>`,...departments.map(d=>`<button class="department-btn ${state.currentDepartment===d?'active':''}" data-department="${d}">${d}</button>`)].join('');}
function render(){const items=records();el.count.textContent=items.length;renderSummary(items);el.hint.textContent=state.query?`تم ترتيب ${items.length} نتيجة حسب قوة المطابقة مع «${state.query}»`:'';el.cards.innerHTML=items.length?items.map(card).join(''):'<div class="empty glass">لا توجد نتائج مطابقة. جرّب رقم الحجز أو جزءًا من الوصف.</div>'}
function selected(){return state.allData.find(r=>r.id===state.selectedId)}
function openDetail(r){state.selectedId=r.id;el.detailDepartment.textContent=clean(r.department)||'غير محدد';el.title.textContent=clean(r.contract_details)||'تفاصيل السجل';el.center.textContent=clean(r.cost_center)||'—';el.booking.textContent=clean(r.booking_number)||'—';el.contract.textContent=clean(r.contract_details)||'—';el.notes.textContent=clean(r.notes)||'لا توجد ملاحظات';el.amount.textContent=money(r.amount_lyd);el.status.textContent=r.needs_review?'تحتاج مراجعة':'مكتملة البيانات';el.status.className=`status ${r.needs_review?'review':'ok'}`;el.dialog.showModal()}
function shareText(r){return [`دليل مراكز التكلفة`,`القسم: ${clean(r.department)||'غير محدد'}`,`مركز التكلفة: ${clean(r.cost_center)||'—'}`,`رقم الحجز: ${clean(r.booking_number)||'—'}`,`تفاصيل العمل: ${clean(r.contract_details)||'—'}`,`القيمة: ${money(r.amount_lyd)}`,`الملاحظات: ${clean(r.notes)||'لا توجد'}`].join('\n')}
function toast(t){el.toast.textContent=t;el.toast.classList.add('show');setTimeout(()=>el.toast.classList.remove('show'),1800)}
async function copy(t){await navigator.clipboard.writeText(t);toast('تم النسخ بنجاح')}
async function share(r){const text=shareText(r);try{if(navigator.share)await navigator.share({title:'بطاقة مركز تكلفة',text});else await copy(text)}catch(e){if(e.name!=='AbortError')await copy(text)}}
el.departmentFilters.addEventListener('click',e=>{const button=e.target.closest('[data-department]');if(!button)return;state.currentDepartment=button.dataset.department;renderDepartments();render()});
el.search.addEventListener('input',e=>{state.query=e.target.value.trim();render()});el.clear.addEventListener('click',()=>{el.search.value='';state.query='';el.search.focus();render()});document.querySelectorAll('.filter-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.currentFilter=b.dataset.filter;render()}));el.cards.addEventListener('click',e=>{const c=e.target.closest('.record');if(!c)return;const r=state.allData.find(x=>x.id===c.dataset.id);if(e.target.closest('[data-action="share"]'))share(r);else openDetail(r)});el.close.addEventListener('click',()=>el.dialog.close());el.dialog.addEventListener('click',e=>{if(e.target===el.dialog)el.dialog.close()});el.share.addEventListener('click',()=>share(selected()));el.copyCenter.addEventListener('click',()=>copy(clean(selected()?.cost_center)));el.copyCard.addEventListener('click',()=>copy(shareText(selected())));
(async()=>{try{const res=await fetch(`./data/cost_centers_initial_data.json?v=${Date.now()}`, { cache: 'no-store' });if(!res.ok)throw new Error('Data unavailable');const payload=await res.json();state.allData=(payload.records||[]).map(r=>({...r,department:clean(r.department||r.source_sheet||'غير محدد'),notes:clean(r.notes),needs_review:Boolean(r.needs_review)}));renderDepartments();render()}catch(e){el.cards.innerHTML='<div class="empty glass">تعذر تحميل البيانات. شغّل المشروع عبر خادم محلي.</div>';console.error(e)}})();


// Theme persistence and controlled splash transition
const themeSelect=document.getElementById('themeSelect');
if(themeSelect){
  themeSelect.value=document.documentElement.dataset.theme||'light';
  themeSelect.addEventListener('change',(event)=>{
    const theme=allowedThemes.includes(event.target.value)?event.target.value:'light';
    document.documentElement.dataset.theme=theme;
    localStorage.setItem(THEME_STORAGE_KEY,theme);
  });
}
window.addEventListener('load',()=>{
  const splash=document.getElementById('splashScreen');
  const minimumDisplay=1800;
  window.setTimeout(()=>splash?.classList.add('is-hidden'),minimumDisplay);
  window.setTimeout(()=>splash?.remove(),minimumDisplay+750);
});
